project:
  useAWS: False 
  awsSetup:
    bucket: projects.irll # working bucket in AWS
    region: ca-central-1 # working AWS region
    rootDomain: irll.net # a fully qualified domain name without 'https://'
    cpu: 2 # int 1,2, or 4
    memory: 10 # int 1-30

  events:
    startServerStep: 1 # int ? #this
    stopServerStep: 13
  id: exp-mario-binary-feedback # Letters, Numbers and '-' only! #only lower case #change this
  live: True # bool
  maxRuntime: 90 # int in minutes.
  name: mario_binary_feedback # str #change this 
  researcher: Edan Meyer
  ssl:
    fullchain: SSL/fullchain.pem # path to fullchain.pem file excluding bucket name
    privkey: SSL/privkey.pem # path to privkey.pem file excluding bucket name
    sslBucket: projects.irll # bucket name for resolving paths above

  steps: #in the step file folder # any number of steps needed with corresponding filenames
    1: consentForm.html
    2: initialMarioSurvey.html
    3: marioPlayInstructions.html
    4: game
    5: round2of3.html
    6: game
    7: feedbackInstructions.html
    8: game
    9: round2of3.html
    10: game
    11: postGameSurvey.html
    12: uuidScreen.html
    13: endScreen.html
    finalStep: endScreen.html #put the file name of the last step again here # required, filename can be same as last numbered step
  teamMembers: Edan # str

trial:
  trial_types:
    - play_game
    - play_game
    - give_feedback
    - give_feedback
  actionBufferLifespan: 1 # int
  maxEpisodes: 1 # int
  maxEpisodeFrames: 14400 # 60 * 60 * 4, 4 min at 60 FPS
  game: SuperMarioBros-v0 # full environment name
  dataFile: episode # episode or trial
  s3upload: True
  validKeys: ['ArrowRight', 'ArrowLeft', 'ArrowDown', 'ArrowUp', 'z', 'x'] # All keys that the player can use
  advancedActionSpace: # the appropriate action space for environment. Order matters
    - []
    - ['ArrowRight']
    - ['ArrowRight', 'z']
    - ['ArrowRight', 'x']
    - ['ArrowRight', 'z', 'x']
    - ['z']
    - ['ArrowLeft']
    - ['ArrowLeft', 'z']
    - ['ArrowLeft', 'x']
    - ['ArrowLeft', 'z', 'x']
    - ['ArrowDown']
    - ['ArrowUp']
  frameRateStepSize: 5 # int Optional if allowFrameRateChange = False
  minFrameRate: 1 # int Optional if allowFrameRateChange = False
  maxFrameRate: 60 # int Optional if allowFrameRateChange = False
  frameskip: 1 # int Optional how many frames to skip for playing game phase
  allowFrameRateChange: False # bool
  startingFrameRate: 60 # int Required
  play_game_ui: # to include ui button set to True, False buttons will not be shown
    left: False
    right: False
    up: False
    down: False
    start: True
    stop: True # TODO: Change back to false
    pause: True
    reset: False
    trainOffline: False
    trainOnline: False
    good: False
    bad: False
    fpsSet: False
    fpsUp: False
    fpsDown: False
  give_feedback_ui: # to include ui button set to True, False buttons will not be shown
    left: False
    right: False
    up: False
    down: False
    start: True
    stop: True # TODO: Change back to false
    pause: True
    reset: False
    trainOffline: False
    trainOnline: False
    good: True
    bad: True
    fpsSet: False
    fpsUp: False
    fpsDown: False