project:
  awsSetup:
    bucket: projects.irll
    containerName: exp-pong-binary-feedback
    cpu: 2
    memory: 10
    region: ca-central-1
    repository: exp-pong-binary-feedback
    repositoryUri: 237796709103.dkr.ecr.ca-central-1.amazonaws.com/exp-pong-binary-feedback
    rootDomain: irll.net
  bucket: projects.irll
  ecsTask: exp-pong-binary-feedback
  events:
    startServerStep: 1
    stopServerStep: 17
  id: exp-pong-binary-feedback
  live: true
  maxRuntime: 90
  name: pong_binary_feedback
  researcher: Edan Meyer
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: consentForm.html
    2: initialPongSurvey.html
    3: pongPlayInstructions.html
    4: game
    5: round2of3.html
    6: game
    7: round3of3.html
    8: game
    9: feedbackInstructions.html
    10: game
    11: round2of3.html
    12: game
    13: round3of3.html
    14: game
    15: postGameSurvey.html
    16: uuidScreen.html
    17: endScreen.html
    finalStep: endScreen.html
  teamMembers: Edan
  useAWS: true
trial:
  actionBufferLifespan: 1
  actionSpace:
  - noop
  - fire
  - up
  - down
  - rightfire
  - leftfire
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  frameRateStepSize: 5
  frameskip: 1
  game: ALE/Pong-v5
  give_feedback_ui:
  - start
  - pause
  - good
  - bad
  maxEpisodeFrames: 14400
  maxEpisodes: 1
  maxFrameRate: 60
  minFrameRate: 1
  play_game_ui:
  - up
  - down
  - start
  - pause
  projectId: exp-pong-binary-feedback
  s3upload: true
  startingFrameRate: 60
  trial_types:
  - play_game
  - play_game
  - play_game
  - give_feedback
  - give_feedback
  - give_feedback
