project:
  awsSetup:
    bucket: projects.irll
    cpu: 2
    memory: 10
    region: ca-central-1
    rootDomain: irll.net
  events:
    startServerStep: 1
    stopServerStep: 16
  id: exp-breakout-binary-feedback
  live: true
  maxRuntime: 20
  name: breakout_binary_feedback
  researcher: Edan Meyer
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: consentForm.html
    2: initialSurvey.html
    3: playInstructions.html
    4: game
    5: nextRound.html
    6: game
    7: nextRound.html
    8: game
    9: feedbackInstructions.html
    10: game
    11: nextRound.html
    12: game
    13: nextRound.html
    14: game
    15: postGameSurvey.html
    16: endScreen.html
    finalStep: endScreen.html
  teamMembers: Edan
  useAWS: false
trial:
  actionBufferLifespan: 1
  actionSpace:
  - noop
  - up
  - right
  - left
  - down
  - upright
  - upleft
  - downright
  - downleft
  allowFrameRateChange: true
  bucket: projects.irll
  dataFile: episode
  frameRateStepSize: 5
  frameskip: 1
  game: ALE/MsPacman-v5
  give_feedback_ui:
  - start
  - stop
  - pause
  - good
  - bad
  maxEpisodes: 1
  maxFrameRate: 60
  minFrameRate: 1
  play_game_ui:
  - left
  - right
  - up
  - down
  - start
  - stop
  - pause
  projectId: exp-breakout-binary-feedback
  s3upload: true
  startingFrameRate: 60
  trial_types:
  - play_game
  - play_game
  - play_game
  - give_feedback
  - give_feedback
  - give_feedback
