project:
  awsSetup:
    bucket: projects.irll
    cpu: 2
    memory: 10
    region: ca-central-1
    rootDomain: irll.net
  events:
    startServerStep: 1
    stopServerStep: 17
  id: exp-mario-binary-feedback
  live: true
  maxRuntime: 90
  name: mario_binary_feedback
  researcher: Edan Meyer
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: consentForm.html
    2: initialMarioSurvey.html
    3: lunarMarioPlayInstructions.html
    4: game
    5: round2of3.html
    6: game
    7: round3of3.html
    8: game
    9: feedbackInstructions.html
    10: game
    11: round2of3.html
    12: game
    13: round3of3.html
    14: game
    15: postGameSurvey.html
    16: uuidScreen.html
    17: endScreen.html
    finalStep: endScreen.html
  teamMembers: Edan
  useAWS: false
trial:
  actionBufferLifespan: 1
  advancedActionSpace:
  - []
  - - ArrowRight
  - - ArrowRight
    - z
  - - ArrowRight
    - x
  - - ArrowRight
    - z
    - x
  - - z
  - - ArrowLeft
  - - ArrowLeft
    - z
  - - ArrowLeft
    - x
  - - ArrowLeft
    - z
    - x
  - - ArrowDown
  - - ArrowUp
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  frameRateStepSize: 5
  frameskip: 1
  game: SuperMarioBros-v0
  give_feedback_ui:
  - start
  - stop
  - pause
  - good
  - bad
  maxEpisodeFrames: 14400
  maxEpisodes: 1
  maxFrameRate: 60
  minFrameRate: 1
  play_game_ui:
  - start
  - stop
  - pause
  projectId: exp-mario-binary-feedback
  s3upload: true
  startingFrameRate: 60
  trial_types:
  - play_game
  - play_game
  - play_game
  - give_feedback
  - give_feedback
  - give_feedback
  validKeys:
  - ArrowRight
  - ArrowLeft
  - ArrowDown
  - ArrowUp
  - z
  - x
