project:
  awsSetup:
    bucket: projects.irll
    cpu: 2
    memory: 10
    region: ca-central-1
    rootDomain: irll.net
  events:
    startServerStep: 1
    stopServerStep: 17
  id: exp-lunar-lander-binary-feedback
  live: true
  maxRuntime: 90
  name: lunar_lander_binary_feedback
  researcher: Edan Meyer
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: consentForm.html
    2: initialLunarLanderSurvey.html
    3: lunarLanderPlayInstructions.html
    4: game
    5: round2of3.html
    6: game
    7: round3of3.html
    8: game
    9: feedbackInstructions.html
    10: game
    11: round2of3.html
    12: game
    13: round3of3.html
    14: game
    15: postGameSurvey.html
    16: uuidScreen.html
    17: endScreen.html
    finalStep: endScreen.html
  teamMembers: Edan
  useAWS: false
trial:
  actionBufferLifespan: 1
  allowFrameRateChange: false
  bucket: projects.irll
  continuousActionSpace:
  - - null
    - - 0
      - 0
  - - []
    - - 0
      - 0
  - - - ArrowLeft
    - - 0
      - -1
  - - - ArrowRight
    - - 0
      - 1
  - - - ArrowLeft
      - ArrowRight
    - - 0
      - 0
  - - - ArrowUp
    - - 1
      - 0
  - - - ArrowLeft
      - ArrowUp
    - - 1
      - -1
  - - - ArrowRight
      - ArrowUp
    - - 1
      - 1
  - - - ArrowLeft
      - ArrowRight
      - ArrowUp
    - - 1
      - 0
  dataFile: episode
  frameRateStepSize: 5
  frameskip: 1
  game: LunarLanderContinuous-v2
  give_feedback_ui:
  - start
  - stop
  - pause
  - good
  - bad
  maxEpisodes: 1
  maxFrameRate: 60
  minFrameRate: 1
  play_game_ui:
  - left
  - right
  - up
  - start
  - stop
  - pause
  projectId: exp-lunar-lander-binary-feedback
  s3upload: true
  startingFrameRate: 15
  trial_types:
  - play_game
  - play_game
  - play_game
  - give_feedback
  - give_feedback
  - give_feedback
  validKeys:
  - ArrowLeft
  - ArrowRight
  - ArrowUp
