trial:
  actionBufferLifespan: 1
  advancedActionSpace:
  - []
  - - ArrowRight
  - - ArrowRight
    - z
  - - ArrowRight
    - x
  - - ArrowRight
    - z
    - x
  - - z
  - - ArrowLeft
  - - ArrowLeft
    - z
  - - ArrowLeft
    - x
  - - ArrowLeft
    - z
    - x
  - - ArrowDown
  - - ArrowUp
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  frameRateStepSize: 5
  frameskip: 1
  game: SuperMarioBros-v0
  give_feedback_ui:
  - start
  - stop
  - pause
  - good
  - bad
  maxEpisodeFrames: 14400
  maxEpisodes: 1
  maxFrameRate: 60
  minFrameRate: 1
  play_game_ui:
  - start
  - stop
  - pause
  projectId: exp-mario-binary-feedback
  s3upload: true
  startingFrameRate: 60
  trial_types:
  - play_game
  - play_game
  - play_game
  - give_feedback
  - give_feedback
  - give_feedback
  validKeys:
  - ArrowRight
  - ArrowLeft
  - ArrowDown
  - ArrowUp
  - z
  - x
